export const PROBLEM_TAGS = [
  "backhand-basics",
  "backhand-into-net",
  "backhand-slice-floating",
  "balls-too-short",
  "cant-hit-lob",
  "cant-self-practice",
  "doubles-formation-confusion",
  "doubles-net-fear",
  "doubles-poach-hesitation",
  "doubles-positioning",
  "environment-probe",
  "first-serve-in",
  "forehand-basics",
  "forehand-no-power",
  "forehand-out",
  "general-improvement",
  "half-volley-late-contact",
  "incoming-slice-trouble",
  "key-point-indecision",
  "late-contact",
  "match-anxiety",
  "mobility-limit",
  "moonball-trouble",
  "movement-slow",
  "net-confidence",
  "no-clear-technique",
  "on-the-run-late-contact",
  "overhead-spacing",
  "overhead-timing",
  "passive-point-construction",
  "plateau-no-progress",
  "pressure-tightness",
  "rally-consistency",
  "recovery-delay",
  "return-under-pressure",
  "running-backhand",
  "running-forehand",
  "safe-short-collapse",
  "second-serve-confidence",
  "second-serve-reliability",
  "serve-accuracy",
  "serve-basics",
  "serve-footwork",
  "serve-rhythm",
  "serve-timing",
  "serve-toss-consistency",
  "serve-toss-inconsistent",
  "slice-depth-control",
  "slice-too-high",
  "slow-preparation",
  "stamina-drop",
  "timing-off",
  "topspin-low",
  "trouble-with-slice",
  "unknown-problem",
  "volley-contact-instability",
  "volley-errors",
  "volley-floating",
  "volley-into-net"
] as const;

export type ProblemTag = typeof PROBLEM_TAGS[number];

const PROBLEM_TAG_SET = new Set<string>(PROBLEM_TAGS);

export function isProblemTag(value: string): value is ProblemTag {
  return PROBLEM_TAG_SET.has(value);
}
